language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - php: 5.4
      env: SYMFONY_VERSION=2.8.*

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install: composer update -n $COMPOSER_FLAGS

script: phpunit --coverage-text
